using System;
using System.Collections.Generic;

namespace BaskentEnerji.Entity.Entities.ExchangeOffice.Office
{
    public class DayClosure : BaseEntity
    {
        public Guid OfficeId { get; set; }
        public Guid VaultId { get; set; }
        public DateTime BusinessDate { get; set; }
        public Guid ClosedByUserId { get; set; }
        public DateTime ClosedAt { get; set; }
        public DayClosureStatus Status { get; set; }
        public Guid? VaultCountId { get; set; }
        public decimal TotalRealizedProfit { get; set; }
        public int TransactionCount { get; set; }
        public string Notes { get; set; }
        public bool IsAutoGenerated { get; set; } = false;
        public Guid? ApprovedByUserId { get; set; }
        public DateTime? ApprovedAt { get; set; }
        public string RejectionNote { get; set; }

        public Office Office { get; set; }
        public Vault Vault { get; set; }
        public User.User ClosedByUser { get; set; }
        public VaultCount VaultCount { get; set; }
        public ICollection<DayClosureDetail> Details { get; set; }
    }

    public class DayClosureDetail : BaseEntity
    {
        public Guid DayClosureId { get; set; }
        public Guid CurrencyId { get; set; }
        public decimal SystemBalance { get; set; }
        public decimal PhysicalCount { get; set; }
        public decimal Discrepancy { get; set; }
        public string DiscrepancyNote { get; set; }
        public decimal WacAtClose { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal OpeningWac { get; set; }

        public DayClosure DayClosure { get; set; }
        public Currency.Currency Currency { get; set; }
    }

    public enum DayClosureStatus
    {
        Open = 1,
        Closed = 2,
        AutoClosed = 3,
        PendingApproval = 4,
        Rejected = 5
    }
}
